# Artifical neural network for Bank Note Authentication using Keras

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import keras

## Part 1 - Data Preprocessing





### Importing the dataset

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Deep Learning Examples/bank_note_data.txt', header = None )

In [ ]:
dataset.head(5)

0       1       2        3  4
0  3.62160  8.6661 -2.8073 -0.44699  0
1  4.54590  8.1674 -2.4586 -1.46210  0
2  3.86600 -2.6383  1.9242  0.10645  0
3  3.45660  9.5228 -4.0112 -3.59440  0
4  0.32924 -4.4552  4.5718 -0.98880  0

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[  3.6216    8.6661   -2.8073   -0.44699]
 [  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]]


In [ ]:
print(y)

[0 0 0 ... 1 1 1]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### 1. Initializing the ANN

In [ ]:
from keras.models import Sequential
ann = Sequential()

### 2. Adding the input layer and the first hidden layer

In [ ]:
from keras.layers import Dense
ann.add(Dene(4,input_dim=4,activation = 'relu'))

### 3. Adding the second hidden layer

In [ ]:
ann.add(Dense(8,activation='relu'))

### 4. Adding the output layer

In [ ]:
ann.add(Dense(1,activation='sigmoid'))

## PART 3 - Training the Artificial Neural Network

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train,y_train, epochs = 100, verbose = 2)

Epoch 1/100
29/29 - 0s - loss: 0.1413 - accuracy: 0.9739
Epoch 2/100
29/29 - 0s - loss: 0.1393 - accuracy: 0.9750
Epoch 3/100
29/29 - 0s - loss: 0.1374 - accuracy: 0.9739
Epoch 4/100
29/29 - 0s - loss: 0.1356 - accuracy: 0.9750
Epoch 5/100
29/29 - 0s - loss: 0.1336 - accuracy: 0.9739
Epoch 6/100
29/29 - 0s - loss: 0.1318 - accuracy: 0.9761
Epoch 7/100
29/29 - 0s - loss: 0.1299 - accuracy: 0.9761
Epoch 8/100
29/29 - 0s - loss: 0.1287 - accuracy: 0.9750
Epoch 9/100
29/29 - 0s - loss: 0.1266 - accuracy: 0.9717
Epoch 10/100
29/29 - 0s - loss: 0.1251 - accuracy: 0.9761
Epoch 11/100
29/29 - 0s - loss: 0.1230 - accuracy: 0.9793
Epoch 12/100
29/29 - 0s - loss: 0.1215 - accuracy: 0.9728
Epoch 13/100
29/29 - 0s - loss: 0.1197 - accuracy: 0.9782
Epoch 14/100
29/29 - 0s - loss: 0.1181 - accuracy: 0.9728
Epoch 15/100
29/29 - 0s - loss: 0.1169 - accuracy: 0.9793
Epoch 16/100
29/29 - 0s - loss: 0.1153 - accuracy: 0.9750
Epoch 17/100
29/29 - 0s - loss: 0.1135 - accuracy: 0.9782
Epoch 18/100
29/29 - 0s

## Part 4 - Making the predictions and evaluating the model

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]

### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(classification_report(y_test, y_pred))

[[254   3]
 [  0 196]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       257
           1       0.98      1.00      0.99       196

    accuracy                           0.99       453
   macro avg       0.99      0.99      0.99       453
weighted avg       0.99      0.99      0.99       453



In [ ]:
#how to save and load model
ann.save('mysupermodel.h5')
from keras.models import load_model
newmodel = load_model('mysupermodel.h5')
newmodel.predict(X_test)

array([[9.42319632e-03],
       [6.36713862e-01],
       [2.63852060e-01],
       [1.03831291e-03],
       [3.89023125e-02],
       [3.12355161e-03],
       [2.48332024e-02],
       [4.81715798e-03],
       [5.58716059e-03],
       [7.19198585e-03],
       [8.64693046e-01],
       [9.83527064e-01],
       [3.98603082e-03],
       [9.56429482e-01],
       [3.54495943e-02],
       [7.84293592e-01],
       [9.61088657e-01],
       [9.66609120e-01],
       [9.95285273e-01],
       [8.13745499e-01],
       [1.44869983e-02],
       [2.77823210e-03],
       [9.17117238e-01],
       [1.35885775e-02],
       [9.97610629e-01],
       [1.00189149e-02],
       [1.03694201e-03],
       [9.70840812e-01],
       [3.59952450e-04],
       [1.04576349e-03],
       [9.66911912e-01],
       [4.85697389e-03],
       [1.40509307e-02],
       [9.94839966e-01],
       [9.90815222e-01],
       [3.42813134e-03],
       [8.45003188e-01],
       [9.52022493e-01],
       [9.82863605e-01],
       [4.26578522e-03],
